### ISSUE TITLE
Aderyn crashes for TempleDao

### ISSUE THREAD

**Issue by TilakMaddy** [Cyfrin/aderyn#574]
Repo source:
https://github.com/TempleDAO/temple/tree/templegold/protocol/contracts

Command:
```
cargo run path/to/temple/protocol/ -o temple.md
```

Output:
```
   Blocking waiting for file lock on build directory
   Compiling aderyn_core v0.1.5 (/Users/tilakmadichetti/Documents/OpenSource/realaderyn/aderyn_core)
   Compiling aderyn_driver v0.1.5 (/Users/tilakmadichetti/Documents/OpenSource/realaderyn/aderyn_driver)
   Compiling aderyn v0.1.5 (/Users/tilakmadichetti/Documents/OpenSource/realaderyn/aderyn)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 16.42s
     Running `target/debug/aderyn ../temple/protocol/ -o temple.md`
Root: "/Users/tilakmadichetti/Documents/OpenSource/temple/protocol", Src: Some(["contracts"]), Include: None, Exclude: Some(["test/forge/", "script/", "node_modules/", "lib/"])
Resolving sources versions by graph ...
Compiling 13 files with Solc 0.5.16+commit.9c3226ce.Darwin.appleclang
Compiling 10 files with Solc 0.6.6+commit.6c089d02.Darwin.appleclang
Compiling 174 files with Solc 0.8.20+commit.a1b79de6.Darwin.appleclang
Compiling 154 files with Solc 0.8.26+commit.8a97fa7a.Darwin.appleclang
Get Detectors
Running 30 detectors
Detectors run, processing found issues
Found issues processed. Printing report
thread 'main' panicked at aderyn_core/src/report/mod.rs:106:70:
called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Helpful analysis (bug cause):
```
[aderyn_core/src/report/mod.rs:107:25] contract_path = "contracts/amm/TempleStableAMMRouter.sol"
[aderyn_core/src/report/mod.rs:107:25] line_no = 148
[aderyn_core/src/report/mod.rs:107:25] src_location = "-1:-1"
```

**Comment by alexroan** [comment]
Attempting to reproduce:
1. Install all dependencies from root - `yarn`
2. `cd protocol`
3. `yarn compile` (this uses hardhat, not foundry. Foundry seems to not compile for me)
4. `aderyn`, gives me the following output:

```
Root: "/Users/alexroan/Documents/Audits/2024-07-templegold/protocol", Src: Some(["contracts"]), Include: None, Exclude: Some(["test/forge/", "script/", "node_modules/", "lib/"])
Resolving sources versions by graph ...
Compiling 13 files with Solc 0.5.16+commit.9c3226ce.Darwin.appleclang
Compiling 174 files with Solc 0.8.20+commit.a1b79de6.Darwin.appleclang
Compiling 10 files with Solc 0.6.6+commit.6c089d02.Darwin.appleclang
Compiling 154 files with Solc 0.8.26+commit.8a97fa7a.Darwin.appleclang
Get Detectors
Running 29 detectors
thread '<unnamed>' panicked at aderyn_core/src/ast/variables.rs:114:13:
internal error: entered unreachable code
stack backtrace:
   0:        0x1012dfe10 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1f3776e0b5c7517d
   1:        0x1013018c0 - core::fmt::write::heedef092c8c0962e
   2:        0x1012dbeac - std::io::Write::write_fmt::h7178e8e2ea928914
   3:        0x1012dfc68 - std::sys_common::backtrace::print::h417292deb95532ed
   4:        0x1012e0e48 - std::panicking::default_hook::{{closure}}::h0cb68f1228c4613a
   5:        0x1012e0b3c - std::panicking::default_hook::h24535936bc1f51de
   6:        0x1012e1700 - std::panicking::rust_panic_with_hook::h5db4d2345b297bed
   7:        0x1012e1104 - std::panicking::begin_panic_handler::{{closure}}::h3fd558f09a0d5492
   8:        0x1012e0298 - std::sys_common::backtrace::__rust_end_short_backtrace::hfc76eebe1ce501b2
   9:        0x1012e0ea0 - _rust_begin_unwind
  10:        0x10134bbb0 - core::panicking::panic_fmt::hc2b459a5bd3dce66
  11:        0x10134bc30 - core::panicking::panic::h65d5df1c072e7907
  12:        0x100ea94a8 - <hashbrown::map::HashMap<K,V,S,A> as core::iter::traits::collect::Extend<(K,V)>>::extend::h3496b765cc910cfc
  13:        0x100efc360 - <aderyn_core::detect::low::zero_address_check::ZeroAddressCheckDetector as aderyn_core::detect::detector::IssueDetector>::detect::hba7058ac49dd90f4
  14:        0x100c8c89c - rayon::iter::plumbing::Folder::consume_iter::h5861b1acaec9b095
  15:        0x100c53a14 - rayon::iter::plumbing::bridge_producer_consumer::helper::h83153987279d79ab
  16:        0x100bf745c - rayon_core::join::join_context::{{closure}}::h007d293329d90bc4
  17:        0x100c53ae8 - rayon::iter::plumbing::bridge_producer_consumer::helper::h83153987279d79ab
  18:        0x100bf745c - rayon_core::join::join_context::{{closure}}::h007d293329d90bc4
  19:        0x100c53ae8 - rayon::iter::plumbing::bridge_producer_consumer::helper::h83153987279d79ab
  20:        0x100c8bc28 - rayon::iter::extend::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend::h7d941ef5877a71fd
  21:        0x100c8c160 - rayon::iter::plumbing::Folder::consume_iter::h2aca6be5183b01b3
  22:        0x100c53384 - rayon::iter::plumbing::bridge_producer_consumer::helper::h12d5846bbb5b03e9
  23:        0x100bf7aa4 - rayon_core::join::join_context::{{closure}}::h4e4ec8aea5acf8a4
  24:        0x100c53454 - rayon::iter::plumbing::bridge_producer_consumer::helper::h12d5846bbb5b03e9
  25:        0x100c3c160 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h527ffc143e9a29ec
  26:        0x101344334 - rayon_core::registry::WorkerThread::wait_until_cold::h7a4521dc43da9eec
  27:        0x1012074a4 - rayon_core::registry::ThreadBuilder::run::ha3dec7539c1d8df5
  28:        0x10120cd94 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb364f9a76f6ce8cb
  29:        0x10120c5e4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h31bfa559b3e96e2d
  30:        0x1012e6144 - std::sys::pal::unix::thread::Thread::new::thread_start::h50a0ef5291b272f3
  31:        0x18a212f94 - __pthread_joiner_wake

```

variables.rs is the `unreachable!()` in this impl:

```rs
impl VariableDeclaration {
    /// Returns the mutability of the variable that was declared.
    ///
    /// This is a helper to check variable mutability across Solidity versions.
    pub fn mutability(&self) -> &Mutability {
        if let Some(mutability) = &self.mutability {
            mutability
        } else if self.constant {
            &Mutability::Constant
        } else if self.state_variable {
            &Mutability::Mutable
        } else {
            unreachable!()
        }
    }
}
```

**Comment by alexroan** [comment]
Yes, we're missing `immutable`. I'll fix this ASAP
